---
apiVersion: v1
kind: Service
metadata:
  name: islandora-transformer
spec:
  selector:
    app: islandora-transformer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-transformer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-transformer
  template:
    metadata:
      labels:
        app: islandora-transformer
    spec:
      containers:
        - name: sentence-transformer
          image: ghcr.io/lehigh-university-libraries/sentence-transformer-service:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8080
              hostPort: 8090
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
