name: lint-build-push
on:
  push:
    tags:
      - "*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          verbose: true

      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  build-push:
    needs: [lint]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
