name: lint-build-push
on:
  push:
    tags:
      - "*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - run: shellcheck docker-entrypoint.sh

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          verbose: true

      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  build-push:
    needs: [lint]
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
